# -*- coding: utf-8 -*-
"""RubinaDas_DataScience_Week2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ik2FYUWl3KHHh_rFuzWrPNRZlXa5twGF

**DATA SCIENCE ASSIGNMENT**

**Python Data Structures and File Handling**

**Task 1: Basic Operations**

Write a Python program that:
1. Accepts two integer inputs from the user.
2. Performs the following operations using arithmetic operators:
*   Addition, Subtraction, Multiplication, Division, Modulus, and Exponentiation.
3. Prints the results in a well-formatted way using f-strings.
"""

# 2 numbers of type int are taken as input from the user
num_1 = int(input("Enter the first number: ").strip())
num_2 = int(input("Enter the second number: ").strip())

addition = num_1 + num_2              # the numbers are added using operator '+'
subtraction = num_1 - num_2           # the difference is calculated using operator '-'
multiplication = num_1 * num_2        # the numbers are multiplied using operator '*'
division = num_1 / num_2              # the division is calculated using operator '/' which will give the result in float
floor_division = num_1 // num_2       # the floor division is calculated using operator '//' with result in int rounding off to the minimum value
modulus = num_1 % num_2               # the remainder is calculated using the opeartor '%'
exponentiation = num_1 ** num_2       # the exponent is calculated using the operator '**'

# All the operation values are printed using f-strings
print(f'{num_1} + {num_2} = {addition}')
print(f'{num_1} - {num_2} = {subtraction}')
print(f'{num_1} * {num_2} = {multiplication}')
print(f'{num_1} / {num_2} = {division}')
print(f'{num_1} // {num_2} = {floor_division}')
print(f'{num_1} % {num_2} = {modulus}')
print(f'{num_1} ** {num_2} = {exponentiation}')

"""**Task 2: Working with Lists and Arrays**
1. Create a list containing at least 10 numbers.
2. Perform the following:
*   Print the length of the list.
*   Find the maximum and minimum value.
*   Add a new element to the list and remove one element.
*   Sort the list in ascending and descending order.
3. Convert the list into a NumPy array and calculate:
*   Mean, Median, and Standard Deviation.
"""

# A list is created with 15 numbers and the list contains integer and float values
numbers = [77, 78.5, 86, 85.3, 99, 100, 10, -12.5, -35.7, -45, 509, -239, -687.9, -700, 888]

length_of_list_numbers = len(numbers)             # len() function returns the length of the list
maximum_element_of_list_numbers = max(numbers)    # max() function returns the maximum value of the list
minimum_element_of_list_numbers = min(numbers)    # min() function returns the maximum value of the list

# The results are printed using f-strings
print(f'The original list: {numbers}')
print(f'Length of the list = {length_of_list_numbers}')
print(f'Maximum value of the list = {maximum_element_of_list_numbers}')
print(f'Minimum value of the list = {minimum_element_of_list_numbers}')

numbers.append(256)   # a new number is added to the list
numbers.remove(100)   # an existing number is deleted from the list

# The list is printed after modification
print(f'The list after adding an element and removing an element: {numbers}')

ascending_order_numbers = sorted(numbers)                   # the list is sorted in ascending order
descending_order_numbers = ascending_order_numbers[::-1]    # the list is sorted in descending order

# The sorted lists are printed
print(f'List in ascending order: {ascending_order_numbers}')
print(f'List in descending order: {descending_order_numbers}')

# numpy module is imported and np is just another reference or alias which will be used further to access the functions and attributes of the module
import numpy as np

arr = np.array(numbers)                   # converting the list into a numpy array
mean = np.mean(numbers)                   # calculates the mean or average of the numpy array
median = np.median(numbers)               # calculates the median of the numpy array
standard_deviation = np.std(numbers)      # calculates the standard deviation of the numpy array

# All the results are printed using f-strings
print(f'The numpy arra: {arr}')
print(f'Validating the type of numpy array: {type(arr)}')
print(f'The mean of the numpy array = {mean}')
print(f'The median of the numpy array = {median}')
print(f'The standard deviation of the numpy array = {standard_deviation}')

"""**Task 3: Dictionaries and Sets**
1. Create a dictionary named student with keys: name, age, course, marks.
2. Print each key-value pair using a loop.
3. Add a new key called grade with a value of your choice.
4. Create a set of unique courses (e.g., {“Python”
,
“Data Science”
,
“AI”
,
“Python”}) and display it.
5. Perform set operations — union, intersection, and difference — between two sets of sample data.
"""

# A dictionary student is created with keys as Name, Age, Course, Marks
student = {
    "Name": "Rubina Das",
    "Age": 25,
    "Course": "Python",
    "Marks": 84.2
}

# Each key-value pairs are printed
for key, value in student.items():
  print(f'{key} = {value}')

# A new key Grade is added to the student dictionary
student['Grade'] = 'A'

# Each key-value pairs are printed after modification of the dictionary
for key, value in student.items():
  print(f'{key} = {value}')

# A set() of name courses is created
courses = {"Python", "Data Science", "AI", "Python", "ML", "DL", "NLP", "Data Analytic", "AI"}

# The set() is printed. Even if we enter duplicate values a set() will always store unique values.
print(f'The courses are: {courses}')
print(f'Validating the whether type of courses is set: {type(courses)}')

# 2 sets are created
set_1 = {5, 10, 15, 20, 25, 30, 35, 40, 45, 50}
set_2 = {10, 20, 30, 40, 50, 60, 70, 80, 90, 100}

print(f'Set_1 = {set_1}')
print(f'Set_2 = {set_2}')
print(f'The union of the sets = {set_1.union(set_2)}')                              # it will print all the elements of both the sets
print(f'The intersection of the sets = {set_1.intersection(set_2)}')                # it will print all the common elements of both the sets
print(f'The difference of the sets (Set_1 - Set_2) = {set_1.difference(set_2)}')    # it will print those elements which are present in set_1 only
print(f'The difference of the sets (Set_2 - Set_1) = {set_2.difference(set_1)}')    # it will print those elements which are present in set_2 only

"""**Task 4: File Handling**
1. Create a text file named student_data.txt.
2. Write the following information into the file (name, course, and marks of at least 5 students).
3. Read the file and display only those students whose marks are above 75.
"""

students = [
    "Rubina Das | AI | 80.8",
    "Soumya Verma | Java | 90",
    "Manas Mondal | Maths | 75",
    "Rahul | English | 50",
    "Veer Singh Rathore | Computer | 85.6"
]

# A file named student_data.txt is created which contains details of students (name, course, marks)

with open('student_data.txt', 'w') as file:
  file.write('\n'.join(students))

print("All students details are printed whose marks is greater than 75 . . .")

# The file is opened in read mode
with open('student_data.txt', 'r') as file:
  for line in file:
    name, course, marks = line.strip().split('|')   # Each student details are splitted into list values

    # Student details are printed where marks is greater than 75
    if float(marks.strip()) > 75.0:
      print(f'Name: {name.strip()}, Course: {course.strip()}, Marks: {float(marks.strip())}')
